//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// stop_primitive.cpp
//
// Code generation for function 'stop_primitive'
//

// Include files
#include "stop_primitive.h"
#include "a_opt_mex_data.h"
#include "evalPrimitiveCoeffs.h"
#include "rt_nonfinite.h"
#include "mwmathutil.h"

// Variable Definitions
static emlrtRSInfo wb_emlrtRSI{
    9,                // lineNo
    "stop_primitive", // fcnName
    "C:\\Users\\corra\\Desktop\\Universit\xc3\xa0 Tr"
    "ento\\Master degree\\2nd year\\Intelligent vehicles and autonomous "
    "driving\\Au"
    "tonomous_driving_simulator\\basic_agent_st\\matlab\\stop_primitive.m" // pathName
};

static emlrtRSInfo xb_emlrtRSI{
    10,               // lineNo
    "stop_primitive", // fcnName
    "C:\\Users\\corra\\Desktop\\Universit\xc3\xa0 Tr"
    "ento\\Master degree\\2nd year\\Intelligent vehicles and autonomous "
    "driving\\Au"
    "tonomous_driving_simulator\\basic_agent_st\\matlab\\stop_primitive.m" // pathName
};

static emlrtRSInfo yb_emlrtRSI{
    14,               // lineNo
    "stop_primitive", // fcnName
    "C:\\Users\\corra\\Desktop\\Universit\xc3\xa0 Tr"
    "ento\\Master degree\\2nd year\\Intelligent vehicles and autonomous "
    "driving\\Au"
    "tonomous_driving_simulator\\basic_agent_st\\matlab\\stop_primitive.m" // pathName
};

static emlrtRSInfo ac_emlrtRSI{
    16,               // lineNo
    "stop_primitive", // fcnName
    "C:\\Users\\corra\\Desktop\\Universit\xc3\xa0 Tr"
    "ento\\Master degree\\2nd year\\Intelligent vehicles and autonomous "
    "driving\\Au"
    "tonomous_driving_simulator\\basic_agent_st\\matlab\\stop_primitive.m" // pathName
};

static emlrtRSInfo cc_emlrtRSI{
    8,                  // lineNo
    "finalOptTimeStop", // fcnName
    "C:\\Users\\corra\\Desktop\\Universit\xc3\xa0 Tr"
    "ento\\Master degree\\2nd year\\Intelligent vehicles and autonomous "
    "driving\\Au"
    "tonomous_driving_simulator\\basic_agent_st\\matlab\\finalOptTimeStop.m" // pathName
};

// Function Definitions
void stop_primitive(const emlrtStack *sp, real_T v0, real_T a0, real_T sf,
                    real_T m[6])
{
  emlrtStack b_st;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;
  b_st.prev = &st;
  b_st.tls = st.tls;
  covrtLogFcn(&emlrtCoverageInstance, 11, 0);
  //  Stopping primitive algorithm
  if (covrtLogCond(&emlrtCoverageInstance, 11, 0, 0, v0 <= 0.0) ||
      covrtLogCond(&emlrtCoverageInstance, 11, 0, 1, sf == 0.0)) {
    covrtLogMcdc(&emlrtCoverageInstance, 11, 0, 0, true);
    covrtLogIf(&emlrtCoverageInstance, 11, 0, 0, true);
    covrtLogBasicBlock(&emlrtCoverageInstance, 11, 0);
    for (int32_T i{0}; i < 6; i++) {
      m[i] = 0.0;
    }
  } else {
    real_T smax;
    real_T tf;
    covrtLogMcdc(&emlrtCoverageInstance, 11, 0, 0, false);
    covrtLogIf(&emlrtCoverageInstance, 11, 0, 0, false);
    st.site = &wb_emlrtRSI;
    tf = 4.0 * (v0 * v0);
    if (covrtLogIf(&emlrtCoverageInstance, 11, 0, 1,
                   tf + 5.0 * a0 * sf < 0.0)) {
      covrtLogBasicBlock(&emlrtCoverageInstance, 11, 1);
      st.site = &xb_emlrtRSI;
      smax = -(tf / (5.0 * a0));
      tf = 10.0 * smax / (2.0 * v0);
    } else {
      covrtLogBasicBlock(&emlrtCoverageInstance, 11, 2);
      smax = sf;
      st.site = &yb_emlrtRSI;
      covrtLogFcn(&emlrtCoverageInstance, 12, 0);
      covrtLogBasicBlock(&emlrtCoverageInstance, 12, 0);
      // finalOptTimeStop
      //     OUT1 = finalOptTimeStop(V0,A0,SF)
      //     This function was generated by the Symbolic Math Toolbox
      //     version 9.1. 29-Nov-2022 16:34:15
      b_st.site = &cc_emlrtRSI;
      tf += a0 * sf * 5.0;
      if (tf < 0.0) {
        emlrtErrorWithMessageIdR2018a(
            &b_st, &emlrtRTEI, "Coder:toolbox:ElFunDomainError",
            "Coder:toolbox:ElFunDomainError", 3, 4, 4, "sqrt");
      }
      tf = muDoubleScalarSqrt(tf);
      tf = sf * 10.0 / (v0 * 2.0 + tf);
    }
    covrtLogBasicBlock(&emlrtCoverageInstance, 11, 3);
    st.site = &ac_emlrtRSI;
    evalPrimitiveCoeffs(v0, a0, smax, 0.0, tf, m);
  }
}

// End of code generation (stop_primitive.cpp)
