function final_opt_vel_pass_var = final_opt_vel_pass(v0,a0,sf,T)
%FINAL_OPT_VEL_PASS
%    FINAL_OPT_VEL_PASS_VAR = FINAL_OPT_VEL_PASS(V0,A0,SF,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Nov-2022 23:07:47

final_opt_vel_pass_var = ((sf.*-1.5e+1+T.*v0.*7.0+T.^2.*a0).*(-1.0./8.0))./T;
