function final_opt_vel_j0_pass_var = final_opt_vel_j0_pass(v0,a0,j0,sf,af,T)
%FINAL_OPT_VEL_J0_PASS
%    FINAL_OPT_VEL_J0_PASS_VAR = FINAL_OPT_VEL_J0_PASS(V0,A0,J0,SF,AF,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-Nov-2022 00:02:27

t2 = T.^2;
final_opt_vel_j0_pass_var = t2.*(j0-1.0./T.^3.*(sf.*2.0e+1-T.*v0.*1.2e+1-a0.*t2.*3.0+af.*t2).*3.0).*(-1.0./2.4e+1);
