function final_opt_time_j0_pass_var = final_opt_time_j0_pass(v0,a0,sf)
%FINAL_OPT_TIME_J0_PASS
%    FINAL_OPT_TIME_J0_PASS_VAR = FINAL_OPT_TIME_J0_PASS(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-Nov-2022 00:07:19

t2 = v0.*5.0;
t3 = v0.^2;
t4 = a0.*sf.*8.0;
t6 = sqrt(5.0);
t5 = t2.*v0;
t7 = t4+t5;
t8 = sqrt(t7);
t9 = t6.*t8;
final_opt_time_j0_pass_var = [(sf.*1.0e+1)./(t2+t9);(sf.*1.0e+1)./(t2-t9)];
