function final_opt_pos_j0_var = final_opt_pos_j0(v0,a0,j0,vf,af,T)
%FINAL_OPT_POS_J0
%    FINAL_OPT_POS_J0_VAR = FINAL_OPT_POS_J0(V0,A0,J0,VF,AF,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Nov-2022 23:44:04

t2 = T.^2;
final_opt_pos_j0_var = (T.^3.*(j0+1.0./T.^3.*(T.*v0.*1.2e+1+T.*vf.*8.0+a0.*t2.*3.0-af.*t2).*3.0))./6.0e+1;
