function out1 = time_min_vel(a0,sf)
%TIME_MIN_VEL
%    OUT1 = TIME_MIN_VEL(A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Nov-2022 23:08:18

out1 = -(sqrt(1.5e+1).*sqrt(-a0.*sf))./a0;
