function vf_j0 = finalOptVelj0(v0,a0,sf,T)
%finalOptVelj0
%    VF_J0 = finalOptVelj0(V0,A0,SF,T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Nov-2022 14:21:16

vf_j0 = ((sf.*-2.0e+1+T.*v0.*1.2e+1+T.^2.*a0.*3.0).*(-1.0./8.0))./T;
