function out1 = finalOptTimeStopj0(v0,a0)
%finalOptTimeStopj0
%    OUT1 = finalOptTimeStopj0(V0,A0)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Nov-2022 14:21:15

out1 = (v0.*-2.0)./a0;
