function sf_j0 = finalOptPosj0(v0,a0,T)
%finalOptPosj0
%    SF_J0 = finalOptPosj0(V0,A0,T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Nov-2022 14:21:15

sf_j0 = T.*(v0.*4.0+T.*a0).*(3.0./2.0e+1);
