function out1 = finalOptTimeVel(a0,sf)
%finalOptTimeVel
%    OUT1 = finalOptTimeVel(A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    29-Nov-2022 16:34:33

out1 = -(sqrt(1.5e+1).*sqrt(-a0.*sf))./a0;
