function out1 = finalOptTimeStop(v0,a0,sf)
%finalOptTimeStop
%    OUT1 = finalOptTimeStop(V0,A0,SF)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    29-Nov-2022 16:34:15

out1 = (sf.*1.0e+1)./(v0.*2.0+sqrt(a0.*sf.*5.0+v0.^2.*4.0));
